
package ioc.femcoworking.view;

import ioc.femcoworking.dto.DTOUsuari;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONObject;
import resources.SimpleDialog;

/**
 * GUI per gestionar les opcions disponibles per a usuaris administradors
 * 
 * @author Marc Ginovart Vega
 */
public class IniciAdministradorView extends javax.swing.JFrame {
    private static String codiAcces;
    
    public IniciAdministradorView() {
        initComponents();
    }
    
    public IniciAdministradorView(String codi) { 
        codiAcces = codi;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLlistarUsuaris = new javax.swing.JButton();
        btnRegistrarUsuari = new javax.swing.JButton();
        btnCanviarContrasenya = new javax.swing.JButton();
        btnTancarSessio = new javax.swing.JButton();
        btnRegistrarOficina = new javax.swing.JButton();
        btnLlistarOficines = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FEM_Coworking");

        jLabel1.setText("Administrador");

        btnLlistarUsuaris.setText("Veure llistat usuaris");
        btnLlistarUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlistarUsuarisActionPerformed(evt);
            }
        });

        btnRegistrarUsuari.setText("Registrar nou usuari");
        btnRegistrarUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuariActionPerformed(evt);
            }
        });

        btnCanviarContrasenya.setText("Canviar meva contrasenya");
        btnCanviarContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanviarContrasenyaActionPerformed(evt);
            }
        });

        btnTancarSessio.setText("Tancar sessió");
        btnTancarSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTancarSessioActionPerformed(evt);
            }
        });

        btnRegistrarOficina.setText("Registrar nova oficina");
        btnRegistrarOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarOficinaActionPerformed(evt);
            }
        });

        btnLlistarOficines.setText("Veure llistat oficines");
        btnLlistarOficines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlistarOficinesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnLlistarUsuaris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegistrarUsuari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRegistrarOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLlistarOficines, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCanviarContrasenya)
                                .addGap(18, 18, 18)
                                .addComponent(btnTancarSessio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 161, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLlistarUsuaris)
                    .addComponent(btnLlistarOficines))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarUsuari)
                    .addComponent(btnRegistrarOficina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCanviarContrasenya)
                    .addComponent(btnTancarSessio))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLlistarUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlistarUsuarisActionPerformed
        new LlistatUsuarisView(codiAcces).setVisible(true);
    }//GEN-LAST:event_btnLlistarUsuarisActionPerformed

    private void btnTancarSessioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTancarSessioActionPerformed
        DTOUsuari usuari = new DTOUsuari();
                        
        try {
            JSONObject responseLogin = usuari.logoutUsuari(codiAcces);
            
            if (200 != responseLogin.getInt("code")) {
                new SimpleDialog().errorMessage(responseLogin.getString("message"));
            } else {
                new SimpleDialog().infoMessage(responseLogin.getString("message"));
                new LoginView().setVisible(true);
                this.dispose();
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTancarSessioActionPerformed

    private void btnCanviarContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanviarContrasenyaActionPerformed
        new CanviContransenyaView(codiAcces).setVisible(true);
    }//GEN-LAST:event_btnCanviarContrasenyaActionPerformed

    private void btnRegistrarUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuariActionPerformed
        new RegistrarUsuariView().setVisible(true);
    }//GEN-LAST:event_btnRegistrarUsuariActionPerformed

    private void btnRegistrarOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarOficinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarOficinaActionPerformed

    private void btnLlistarOficinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlistarOficinesActionPerformed
        new LlistatOficinesView(codiAcces).setVisible(true);
    }//GEN-LAST:event_btnLlistarOficinesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciAdministradorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanviarContrasenya;
    private javax.swing.JButton btnLlistarOficines;
    private javax.swing.JButton btnLlistarUsuaris;
    private javax.swing.JButton btnRegistrarOficina;
    private javax.swing.JButton btnRegistrarUsuari;
    private javax.swing.JButton btnTancarSessio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
