
package ioc.femcoworking.view;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import ioc.femcoworking.dto.DTOOficina;
import ioc.femcoworking.vo.OficinaVO;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
import java.util.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import resources.SimpleDialog;

/**
 * GUI per a mostrar el llistat d'usuaris del sistema
 * 
 * @author Marc Ginovart Vega
 */
public class LlistatOficinesView extends javax.swing.JFrame {
    private static String codiAcces;
    private static final Integer EDITAR = 0;
    private static final Integer DESHABILITAR = 1;
    
    public LlistatOficinesView(String codi) {
        codiAcces = codi;
        initComponents();
        carregarLlistatOficines(codiAcces);
    }
    
    public LlistatOficinesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        taulaOficines = new javax.swing.JTable();

        setTitle("FEM_Coworking");

        jLabel1.setText("Administrador / Llistat Oficines");

        taulaOficines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taulaOficines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaOficinesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taulaOficines);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taulaOficinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaOficinesMouseClicked
        Integer index = taulaOficines.getSelectedRow();
        TableModel model = taulaOficines.getModel();
        
        String idOficina = model.getValueAt(index, 0).toString();
        String nom = model.getValueAt(index, 1).toString();
        String tipus = model.getValueAt(index, 2).toString();
        String capacitat = model.getValueAt(index, 3).toString();
        String preu = model.getValueAt(index, 4).toString();
        String serveis = model.getValueAt(index, 5).toString();
        String direccio = model.getValueAt(index, 6).toString();
        String poblacio = model.getValueAt(index, 7).toString();
        String provincia = model.getValueAt(index, 8).toString();
        String habilitada = model.getValueAt(index, 9).toString();
        String eliminada = model.getValueAt(index, 10).toString();
                
        InformacioOficinaView informacioOficinaView = new InformacioOficinaView(codiAcces, idOficina);
        
        informacioOficinaView.inputNom.setText(nom);
        informacioOficinaView.selectCategoria.setSelectedItem(tipus);
        informacioOficinaView.inputCapacitat.setText(capacitat);
        informacioOficinaView.inputPreu.setText(preu);
        informacioOficinaView.txtAreaServeis.setText(serveis);
        informacioOficinaView.inputDireccio.setText(direccio);
        informacioOficinaView.inputPoblacio.setText(poblacio);
        informacioOficinaView.inputProvincia.setText(provincia);
        informacioOficinaView.chkHabilitat.setSelected(Boolean.parseBoolean(habilitada));
        informacioOficinaView.chkEliminat.setSelected(Boolean.parseBoolean(eliminada));
        
        Integer accioUsuari= new SimpleDialog().optionMessage("Editar o eliminar oficina?", "Editar", "Eliminar");
        if (accioUsuari == EDITAR) {
            informacioOficinaView.setVisible(true);
        } else if (accioUsuari == DESHABILITAR) {
            if (Boolean.parseBoolean(eliminada)) {
                new SimpleDialog().infoMessage("Oficina ja marcada com eliminada");
            } else {
                baixaOficina(codiAcces, idOficina);                
            }
        }
    }//GEN-LAST:event_taulaOficinesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlistatOficinesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlistatOficinesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlistatOficinesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlistatOficinesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlistatOficinesView().setVisible(true);
            }
        });
    }
    
    private void carregarLlistatOficines(String codiAcces) {        
        DTOOficina oficina = new DTOOficina();
        
        try {
            JSONObject response = oficina.llistatOficines(codiAcces);
            
            if (200 != response.getInt("code")) {
                System.out.println(response.getString("message"));
                JSONObject jsonResponse = new JSONObject(response.getString("message"));
                new SimpleDialog().errorMessage(jsonResponse.get("message").toString());
            } else {
                List<OficinaVO> llistatOficines = new ObjectMapper().readValue(
                    response.getString("message"),
                    new TypeReference<List<OficinaVO>>() {}
                );
                
                DefaultTableModel model = new DefaultTableModel();
                
                model.setColumnIdentifiers(new Object[]{
                    "Id",
                    "Nom",
                    "Tipus",
                    "Capacitat",
                    "Preu",
                    "Serveis",
                    "Direcció",
                    "Població",
                    "Provincia",
                    "Habilitada",
                    "Eliminada"
                });
                
                for (OficinaVO oficinaInfo: llistatOficines) {
                    ObjectMapper objectMapper = new ObjectMapper();
                    String modelData = objectMapper.writeValueAsString(oficinaInfo);
                    System.out.println("oficina >> "+modelData);
                    model.addRow(new Object[]{
                        oficinaInfo.getIdOficina(),
                        oficinaInfo.getNom(),
                        oficinaInfo.getTipus(),
                        oficinaInfo.getCapacitat(),
                        oficinaInfo.getPreu(),
                        oficinaInfo.getServeis(),
                        oficinaInfo.getDireccio(),
                        oficinaInfo.getPoblacio(),
                        oficinaInfo.getProvincia(),
                        oficinaInfo.getHabilitada(),
                        oficinaInfo.isEliminat(),
                    });
                }
                
                taulaOficines.setModel(model);
                
                taulaOficines.getColumnModel().removeColumn(taulaOficines.getColumnModel().getColumn(0));
                
                
            }
            
        } catch (IOException ex) {
            Logger.getLogger(LlistatOficinesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void baixaOficina(String codiAcces, String idOficina) {
        DTOOficina oficina = new DTOOficina();
        
        try {
            JSONObject response = oficina.baixaOficina(codiAcces, idOficina);
            
            if (200 != response.getInt("code")) {
                System.out.println(response.getString("message"));
                JSONObject jsonResponse = new JSONObject(response.getString("message"));
                new SimpleDialog().errorMessage(jsonResponse.get("message").toString());
            } else {
               new SimpleDialog().infoMessage(response.getString("message"));
               taulaOficines.repaint();
               carregarLlistatOficines(codiAcces);
            }
        } catch (IOException ex) {
            Logger.getLogger(LlistatOficinesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable taulaOficines;
    // End of variables declaration//GEN-END:variables
}
