
package ioc.femcoworking.view;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import ioc.femcoworking.dto.DTOFactura;
import ioc.femcoworking.dto.DTOReserva;
import ioc.femcoworking.vo.FacturaVO;
import ioc.femcoworking.vo.ReservaVO;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
import java.util.*;
import javax.swing.table.TableModel;
import resources.SimpleDialog;

/**
 * GUI per a mostrar el llistat d'usuaris del sistema
 * 
 * @author Marc Ginovart Vega
 */
public class LlistatFacturesView extends javax.swing.JFrame {
    private static String codiAcces;
    private static final Integer SI_ELIMINAR = 0;
    private static final Integer NO_ELIMINAR = 1;
    
    public LlistatFacturesView(String codi) {
        codiAcces = codi;
        initComponents();        
        carregarLlistatFactures(codiAcces);
    }
    
    public LlistatFacturesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        taulaFactures = new javax.swing.JTable();

        setTitle("FEM_Coworking");

        jLabel1.setText("Llistat Factures");

        taulaFactures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taulaFactures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaFacturesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taulaFactures);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taulaFacturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaFacturesMouseClicked
        
        Integer index = taulaFactures.getSelectedRow();
        TableModel model = taulaFactures.getModel();
                
        String idFactura = model.getValueAt(index, 0).toString();
        
        Integer accioUsuari= new SimpleDialog().optionMessage("Eliminar factura?", "Si", "No");
        if (accioUsuari == SI_ELIMINAR) {
            eliminarFactura(codiAcces, idFactura);
        }
    }//GEN-LAST:event_taulaFacturesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlistatFacturesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlistatFacturesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlistatFacturesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlistatFacturesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlistatFacturesView().setVisible(true);
            }
        });
    }
    
    /**
     * Carregar de dades el llistat amb factures
     * 
     * @param codiAcces 
     */
    private void carregarLlistatFactures(String codiAcces) {  
        DTOFactura factura = new DTOFactura();
        
        try {
            JSONObject response = factura.llistatFactures(codiAcces);
            
            if (200 != response.getInt("code")) {
                System.out.println(response.getString("message"));
                new SimpleDialog().errorMessage(response.getString("message"));
            } else {
                List<FacturaVO> llistatFactura = new ObjectMapper().readValue(
                    response.getString("message"), 
                    new TypeReference<List<FacturaVO>>() {}
                );
                
                DefaultTableModel model = new DefaultTableModel();
        
                model.setColumnIdentifiers(new Object[]{
                    "IdFactura",
                    "Nom Oficina",
                    "Nom Usuari",
                    "SubTotal",
                    "Impostos",
                    "Total"
                });
                
                String pattern = "dd-MM-yyyy";
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                
                for (FacturaVO facturaInfo: llistatFactura) {
                    //System.out.println(String.valueOf(facturaInfo));
                    model.addRow(new Object[]{
                        facturaInfo.getIdFactura(),
                        facturaInfo.getIdReserva().getIdOficina().getNom(),
                        facturaInfo.getIdUsuari().getNom(),
                        facturaInfo.getSubTotal(),
                        facturaInfo.getImpostos(),
                        facturaInfo.getTotal()
                    });
                }
                
                taulaFactures.setModel(model); 
                //taulaFactures.getColumnModel().removeColumn(taulaFactures.getColumnModel().getColumn(0));
            }
            
        } catch (IOException ex) {
            Logger.getLogger(LlistatFacturesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Eliminar factura
     * 
     * @param codiAcces
     * @param idReserva 
     */
    private void eliminarFactura(String codiAcces, String idReserva) {
        DTOFactura factura = new DTOFactura();        
        
        try {
            JSONObject response = factura.eliminarFactura(codiAcces, idReserva);
            
            if (200 != response.getInt("code")) {
                System.out.println(response.getString("message"));
                JSONObject jsonResponse = new JSONObject(response.getString("message"));
                new SimpleDialog().errorMessage(jsonResponse.get("message").toString());
            } else {
                new SimpleDialog().infoMessage(response.getString("message"));
                taulaFactures.repaint();
                carregarLlistatFactures(codiAcces);
            }
        } catch (IOException ex) {
            Logger.getLogger(LlistatOficinesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable taulaFactures;
    // End of variables declaration//GEN-END:variables
}
